import json
from pathlib import Path
nb_path = Path('data_analysis.ipynb')
nb = json.loads(nb_path.read_text())
for cell in nb['cells']:
    if cell.get('cell_type') == 'code':
        src = ''.join(cell.get('source', []))
        if 'RESULTS_DIR = PROJECT_ROOT / "ReIFE" / "results"' in src:
            cell['source'] = [
                "PROJECT_ROOT = Path.cwd()\n",
                "RESULTS_DIR = PROJECT_ROOT / \"results\"\n",
                "\n",
                "DATASET_CONFIG = {\n",
                "    \"llm_grader\": {\n",
                "        \"display\": \"LLM Grader\",\n",
                "        \"result\": RESULTS_DIR / \"llm_grader\" / \"pointwise_results.jsonl\",\n",
                "        \"meta\": RESULTS_DIR / \"llm_grader\" / \"summary.json\",\n",
                "    },\n",
                "    \"biggen_bench\": {\n",
                "        \"display\": \"BiGGen-Bench\",\n",
                "        \"result\": RESULTS_DIR / \"biggen_bench\" / \"pointwise_results.jsonl\",\n",
                "        \"meta\": RESULTS_DIR / \"biggen_bench\" / \"summary.json\",\n",
                "    },\n",
                "    \"flask\": {\n",
                "        \"display\": \"FLASK\",\n",
                "        \"result\": RESULTS_DIR / \"flask\" / \"pointwise_results.jsonl\",\n",
                "        \"meta\": RESULTS_DIR / \"flask\" / \"summary.json\",\n",
                "    },\n",
                "    \"mt_bench\": {\n",
                "        \"display\": \"MT-Bench\",\n",
                "        \"result\": RESULTS_DIR / \"mt_bench\" / \"pointwise_results.jsonl\",\n",
                "        \"meta\": RESULTS_DIR / \"mt_bench\" / \"summary.json\",\n",
                "        \"optional\": True,\n",
                "    },\n",
                "    \"chatbot_arena\": {\n",
                "        \"display\": \"Chatbot Arena\",\n",
                "        \"result\": RESULTS_DIR / \"chatbot_arena\" / \"pointwise_results.jsonl\",\n",
                "        \"meta\": RESULTS_DIR / \"chatbot_arena\" / \"summary.json\",\n",
                "        \"optional\": True,\n",
                "    },\n",
                "}\n",
            ]
        elif 'def build_dataset_summary(dataset_key: str, prefix: str)' in src:
            cell['source'] = [
                "def build_dataset_summary(dataset_key: str, config: Dict[str, Path]) -> Dict[str, Any]:\n",
                "    result_path = config.get(\"result\")\n",
                "    meta_path = config.get(\"meta\")\n",
                "    if result_path is None or not result_path.exists():\n",
                "        raise FileNotFoundError(\n",
                "            f\"Could not locate result file for '{dataset_key}' at {result_path}.\"\n",
                "        )\n",
                "\n",
                "    meta_payload: Dict[str, Any] = {}\n",
                "    if meta_path is not None and meta_path.exists():\n",
                "        meta_payload = json.loads(meta_path.read_text(encoding=\"utf-8\"))\n",
                "\n",
                "    analysis_sections = analyze_pointwise_results(\n",
                "        result_path,\n",
                "        meta_path=meta_path,\n",
                "        include_meta=True,\n",
                "    )\n",
                "\n",
                "    records = load_records(result_path)\n",
                "    frame = records_to_frame(records, dataset_key)\n",
                "\n",
                "    model_scores = frame[\"model_score\"].dropna()\n",
                "    human_scores = frame[\"human_mean\"].dropna()\n",
                "    max_scores = frame[\"max_score\"].dropna()\n",
                "\n",
                "    stats = {\n",
                "        \"dataset\": DISPLAY_NAMES.get(dataset_key, dataset_key),\n",
                "        \"examples\": int(len(frame)),\n",
                "        \"with_human\": int(frame[\"human_mean\"].notna().sum()),\n",
                "        \"model_mean\": float(model_scores.mean()) if not model_scores.empty else math.nan,\n",
                "        \"model_std\": float(model_scores.std()) if not model_scores.empty else math.nan,\n",
                "        \"human_mean\": float(human_scores.mean()) if not human_scores.empty else math.nan,\n",
                "        \"max_score\": float(max_scores.max()) if not max_scores.empty else math.nan,\n",
                "        \"pearson_corr\": meta_payload.get(\"pearson_corr\"),\n",
                "        \"result_path\": result_path,\n",
                "        \"meta_path\": meta_path,\n",
                "    }\n",
                "\n",
                "    diff_scores = frame[\"score_diff\"].dropna()\n",
                "    diff_std = float(diff_scores.std()) if not diff_scores.empty else 0.0\n",
                "    diff_mean = float(diff_scores.mean()) if not diff_scores.empty else 0.0\n",
                "    if diff_scores.empty:\n",
                "        outliers = frame.iloc[0:0]\n",
                "    else:\n",
                "        threshold = diff_mean + 2 * diff_std\n",
                "        outliers = frame[frame[\"abs_diff\"] > threshold]\n",
                "\n",
                "    top_examples = frame.sort_values(\"model_score\", ascending=False).head(5)\n",
                "    bottom_examples = frame.sort_values(\"model_score\", ascending=True).head(5)\n",
                "    largest_diffs = frame.sort_values(\"abs_diff\", ascending=False).head(5)\n",
                "\n",
                "    summary = {\n",
                "        \"key\": dataset_key,\n",
                "        \"display_name\": DISPLAY_NAMES.get(dataset_key, dataset_key),\n",
                "        \"config\": config,\n",
                "        \"result_path\": result_path,\n",
                "        \"meta_path\": meta_path,\n",
                "        \"records\": records,\n",
                "        \"meta\": meta_payload,\n",
                "        \"analysis\": analysis_sections,\n",
                "        \"analysis_report\": render_analysis(analysis_sections),\n",
                "        \"dataframe\": frame,\n",
                "        \"stats\": stats,\n",
                "        \"top_examples\": top_examples[[\"id\", \"model_score\", \"human_mean\", \"score_diff\"]],\n",
                "        \"bottom_examples\": bottom_examples[[\"id\", \"model_score\", \"human_mean\", \"score_diff\"]],\n",
                "        \"largest_diffs\": largest_diffs[[\"id\", \"model_score\", \"human_mean\", \"score_diff\"]],\n",
                "        \"outliers\": outliers[[\"id\", \"model_score\", \"human_mean\", \"score_diff\"]],\n",
                "    }\n",
                "    return summary\n",
            ]
        elif 'DATASET_SUMMARIES: Dict[str, Dict[str, Any]] = {}' in src:
            cell['source'] = [
                "DATASET_SUMMARIES: Dict[str, Dict[str, Any]] = {}\n",
                "for key, cfg in DATASET_CONFIG.items():\n",
                "    if cfg.get(\"optional\") and not cfg[\"result\"].exists():\n",
                "        continue\n",
                "    try:\n",
                "        DATASET_SUMMARIES[key] = build_dataset_summary(key, cfg)\n",
                "    except FileNotFoundError as exc:\n",
                "        display(Markdown(f\":warning: {exc}\"))\n",
                "\n",
                "AVAILABLE_DATASETS = list(DATASET_SUMMARIES.keys())\n",
                "if not AVAILABLE_DATASETS:\n",
                "    raise RuntimeError(\n",
                "        \"No datasets were loaded. Generate evaluation results before running this notebook.\"\n",
                "    )\n",
            ]

nb_path.write_text(json.dumps(nb))
